# Generated by Django 3.1.7 on 2021-02-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('video', models.FileField(upload_to='', verbose_name='Видео')),
                ('duration', models.CharField(max_length=255, verbose_name='Длительность')),
                ('periodicity', models.CharField(max_length=255, verbose_name='Периодичность')),
                ('level', models.CharField(choices=[('Простой', 'Простой'), ('Средний', 'Средний'), ('Продвинутый', 'Продвинутый')], max_length=255, verbose_name='Уровень сложности')),
                ('image', models.ImageField(upload_to='', verbose_name='Превью')),
                ('description', models.TextField(verbose_name='Описание')),
                ('value', models.TextField(verbose_name='Польза')),
            ],
            options={
                'verbose_name': 'Тренировка',
                'verbose_name_plural': 'Тренировки',
            },
        ),
    ]
