# Generated by Django 3.1.7 on 2021-02-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_trouble'),
    ]

    operations = [
        migrations.AddField(
            model_name='trouble',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Превью'),
        ),
    ]
