# Generated by Django 3.1.7 on 2021-02-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0004_trouble_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='sex',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F')], default='M', max_length=1, verbose_name='Пол'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workout',
            name='troubles',
            field=models.ManyToManyField(to='workout.Trouble', verbose_name='Проблемы'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='periodicity',
            field=models.CharField(max_length=1, verbose_name='Периодичность'),
        ),
    ]
