# Generated by Django 3.1.7 on 2021-02-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0005_auto_20210224_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trouble',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
    ]
