<<<<<<< HEAD
# Generated by Django 3.1.7 on 2021-02-25 13:29
=======
# Generated by Django 3.1.7 on 2021-02-25 14:08
>>>>>>> d23c3407b89679c29a8a44b2d470490263ae3583

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210224_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Почта')),
                ('password', models.CharField(max_length=255, verbose_name='Почта')),
            ],
            options={
                'verbose_name': 'Администратор',
                'verbose_name_plural': 'Администраторы',
                'ordering': ['id'],
            },
        ),
    ]
